sonar.projectKey=Eifel42_feature-hypotheses-simulation-public
sonar.organization=eifel42
sonar.projectName=Feature Hypotheses Simulation
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.sources=apps/fhs/src
sonar.tests=apps/fhs/tests
sonar.python.version=3.14

sonar.inclusions=apps/fhs/src/**
sonar.test.inclusions=apps/fhs/tests/**
sonar.exclusions=**/.git/**,**/.venv/**,**/__pycache__/**,**/.ipynb_checkpoints/**,**/.mypy_cache/**,**/.pytest_cache/**,**/.ruff_cache/**,build-output/**,apps/fhs/tests/**,apps/fhs/notebooks/**,apps/fhs/config/**,apps/fhs-arc42-doc/**,cicd/**,scripts/**,**/*.ipynb,**/*.md,Makefile
sonar.coverage.exclusions=apps/fhs/tests/**,apps/fhs/notebooks/**,apps/fhs/config/**,apps/fhs-arc42-doc/**,cicd/**,scripts/**,**/*.ipynb,**/*.md,Makefile

sonar.python.coverage.reportPaths=build-output/quality/coverage.xml
sonar.python.xunit.reportPath=build-output/test-results/junit-quality.xml

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
