# Project: FHS (Feature Hypotheses Simulation)
# Copyright: Eifel42 Stefan Zils 2026
# License: See LICENSE and README.md
#
# Disclaimer: This software is provided "as is", without warranty of any kind,
# express or implied, including but not limited to the warranties of
# merchantability, fitness for a particular purpose, and noninfringement.
# In no event shall the authors or copyright holders be liable for any claim,
# damages or other liability, whether in an action of contract, tort or
# otherwise, arising from, out of or in connection with the software or the
# use or other dealings in the software.

"""FHS Domain Model: entities, value objects, aggregates, events, exceptions."""

from .entities import (
    CancellationConfig,
    DelayModelConfig,
    DeliveryRiskConfig,
    Feature,
    ScenarioConfig,
    ScenarioMetadata,
    ScenarioRiskModel,
)
from .events import (
    DomainEvent,
    ScenarioConfigurationChanged,
)
from .exceptions import (
    CorrelationMatrixError,
    FHSException,
    InsufficientDataError,
    PortfolioOptimizationError,
    SimulationError,
    ValidationError,
)
from .repositories import FeatureRepository
from .value_objects import (
    BetaParameters,
    Budget,
    BudgetCheckResult,
    BudgetFrontierRow,
    BudgetRiskRow,
    ClusterRisk,
    ComponentRiskResult,
    ConcentrationResult,
    ConfidenceLevel,
    CorrelationPair,
    CorrelationResult,
    CorrelationStatistics,
    DecisionDimension,
    DeliverySimulationResult,
    DeliveryStressResult,
    DiversificationMetrics,
    ExecutiveDecisionResult,
    FeatureBudgetCheckRow,
    FeatureOperatingCostStats,
    FeatureRanking,
    FeatureRankingRow,
    FeatureRiskProfile,
    FeatureSensitivityResult,
    FinancialViewResult,
    IndividualRiskMetrics,
    IrrAssessment,
    IrrSummary,
    LossMetrics,
    LossProfile,
    MultiYearLayer,
    MultiYearLayerYear,
    MultiYearPnLMeta,
    MultiYearPnLResult,
    MultiYearResult,
    MultiYearRiskProbabilities,
    NegativeScoreComparisonRow,
    NegativeScoreFeature,
    NegativeScoreReport,
    NpvAssessment,
    NpvSummary,
    OperatingCostResult,
    OptimizationResult,
    OptimizationStrategy,
    PLVariantRow,
    PnLAssessment,
    PortfolioMetrics,
    PortfolioPLVariants,
    PortfolioPnLLayers,
    PortfolioProfitabilityResult,
    PortfolioRiskLayers,
    PortfolioRiskMeta,
    PortfolioRiskResult,
    PortfolioSensitivityRow,
    PortfolioSnapshot,
    ProfitabilityResult,
    RetentionMatrix,
    RetentionRow,
    RiskContributionResult,
    RiskFactorContribution,
    RiskFactorShapley,
    RiskHitRates,
    RiskLayerStats,
    RiskManagementROI,
    RiskMetric,
    RiskProbabilities,
    RiskSimulationState,
    SensitivityDetail,
    SensitivityDriver,
    ShapleyAttribution,
    ShapleyContribution,
    SimulationResult,
    SprintPlan,
    StrategyCategoryCostRow,
    TornadoRow,
    WaterfallRow,
    WaterfallSummary,
    YearResult,
)
from .value_objects.simulation_config import DEFAULT_CONFIG, SimulationConfig

__all__ = [
    "DEFAULT_CONFIG",
    "BetaParameters",
    "Budget",
    "BudgetCheckResult",
    "BudgetFrontierRow",
    "BudgetRiskRow",
    "CancellationConfig",
    "ClusterRisk",
    "ComponentRiskResult",
    "ConcentrationResult",
    "ConfidenceLevel",
    "CorrelationMatrixError",
    "CorrelationPair",
    "CorrelationResult",
    "CorrelationStatistics",
    "DecisionDimension",
    "DelayModelConfig",
    "DeliveryRiskConfig",
    "DeliverySimulationResult",
    "DeliveryStressResult",
    "DiversificationMetrics",
    "DomainEvent",
    "ExecutiveDecisionResult",
    "FHSException",
    "Feature",
    "FeatureBudgetCheckRow",
    "FeatureOperatingCostStats",
    "FeatureRanking",
    "FeatureRankingRow",
    "FeatureRepository",
    "FeatureRiskProfile",
    "FeatureSensitivityResult",
    "FinancialViewResult",
    "IndividualRiskMetrics",
    "InsufficientDataError",
    "IrrAssessment",
    "IrrSummary",
    "LossMetrics",
    "LossProfile",
    "MultiYearLayer",
    "MultiYearLayerYear",
    "MultiYearPnLMeta",
    "MultiYearPnLResult",
    "MultiYearResult",
    "MultiYearRiskProbabilities",
    "NegativeScoreComparisonRow",
    "NegativeScoreFeature",
    "NegativeScoreReport",
    "NpvAssessment",
    "NpvSummary",
    "OperatingCostResult",
    "OptimizationResult",
    "OptimizationStrategy",
    "PLVariantRow",
    "PnLAssessment",
    "PortfolioMetrics",
    "PortfolioOptimizationError",
    "PortfolioPLVariants",
    "PortfolioPnLLayers",
    "PortfolioProfitabilityResult",
    "PortfolioRiskLayers",
    "PortfolioRiskMeta",
    "PortfolioRiskResult",
    "PortfolioSensitivityRow",
    "PortfolioSnapshot",
    "ProfitabilityResult",
    "RetentionMatrix",
    "RetentionRow",
    "RiskContributionResult",
    "RiskFactorContribution",
    "RiskFactorShapley",
    "RiskHitRates",
    "RiskLayerStats",
    "RiskManagementROI",
    "RiskMetric",
    "RiskProbabilities",
    "RiskSimulationState",
    "ScenarioConfig",
    "ScenarioConfigurationChanged",
    "ScenarioMetadata",
    "ScenarioRiskModel",
    "SensitivityDetail",
    "SensitivityDriver",
    "ShapleyAttribution",
    "ShapleyContribution",
    "SimulationConfig",
    "SimulationError",
    "SimulationResult",
    "SprintPlan",
    "StrategyCategoryCostRow",
    "TornadoRow",
    "ValidationError",
    "WaterfallRow",
    "WaterfallSummary",
    "YearResult",
]
